import os


DROPBOX_APP_KEY = os.environ['DROPBOX_APP_KEY']
DROPBOX_APP_SECRET = os.environ['DROPBOX_APP_SECRET']
DROPBOX_APP_FOLDER = os.environ['DROPBOX_APP_FOLDER']
DROPBOX_ACCESS_TOKEN = os.environ['DROPBOX_ACCESS_TOKEN']
XERO_CONSUMER_KEY = os.environ['XERO_CONSUMER_KEY']
XERO_CONSUMER_SECRET = os.environ['XERO_CONSUMER_SECRET']
