version: '3'

services:
  # postgres sql db
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: 
      - internal

  # Redis
  redis:
    image: redis:2.8.19
    networks:
      - internal
  
  # RabbitMQ
  rabbit:
    image: rabbitmq
    environment:
      RABBIT_MQ_DEFAULT_USER: ${RABBIT_USER}
      RABBIT_MQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - "5672:5672" # we forward this port because its useful for debugging
      - "15672:15672" # here we can access rabbitmq management plugin
    networks: 
      - internal

  # Django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: /app/run_web.sh
    environment:
      PORT: 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8001:80"
    networks: 
      - internal
      - proxy

  
  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/run_celery.sh
    volumes:
      - .:/app
    networks: 
      - internal


  # Celery beat
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/run_beat.sh
    volumes:
      - .:/app
    networks: 
      - internal

volumes:
  postgres:
  mongo:

networks: 
  proxy:
    external: true
  internal:
    external: false
