# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('character_code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Character Code')),
                ('description', models.CharField(max_length=500, verbose_name='Project Type')),
            ],
            options={
                'verbose_name': 'Project Type',
            },
        ),
        migrations.CreateModel(
            name='ServiceConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('slack', 'Slack'), ('ftrack', 'ftrack'), ('dropbox', 'dropbox'), ('xero', 'Xero'), ('googlegroups', 'Google groups')], max_length=200, verbose_name='Service Name')),
                ('connection_name', models.CharField(blank=True, max_length=200)),
                ('identifier', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucid_api.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucid_api.ProjectType'),
        ),
    ]
