# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('slack_id', models.CharField(max_length=200)),
                ('ftrack_id', models.CharField(max_length=200)),
                ('dropbox_id', models.CharField(max_length=200)),
                ('xero_id', models.CharField(max_length=200)),
                ('googlegroup_id', models.CharField(max_length=200)),
            ],
        ),
    ]
