# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconnection',
            name='connection_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='lucid_api.Project'),
        ),
    ]
