# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Identifier',
        ),
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='old', max_length=200, verbose_name='Project Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='dropbox_id',
            field=models.CharField(max_length=200, verbose_name='Dropbox Folder ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ftrack_id',
            field=models.CharField(max_length=200, verbose_name='ftrack Project ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='googlegroup_id',
            field=models.CharField(max_length=200, verbose_name='Google Group ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slack_id',
            field=models.CharField(max_length=200, verbose_name='Slack Channel ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='xero_id',
            field=models.CharField(max_length=200, verbose_name='Xero Tracking Category ID'),
        ),
    ]
