# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconnection',
            name='service_name',
            field=models.CharField(choices=[(b'dropbox_service', b'Dropbox'), (b'ftrack_service', b'ftrack'), (b'groups_service', b'Google Groups'), (b'lucille_service', b'Lucille Service'), (b'slack_service', b'Slack'), (b'xero_service', b'Xero')], max_length=200, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='templateserviceconnection',
            name='service_name',
            field=models.CharField(choices=[(b'dropbox_service', b'Dropbox'), (b'ftrack_service', b'ftrack'), (b'groups_service', b'Google Groups'), (b'lucille_service', b'Lucille Service'), (b'slack_service', b'Slack'), (b'xero_service', b'Xero')], max_length=200, verbose_name='Service Name'),
        ),
    ]
