# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0002_auto_20171202_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dropbox_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dropbox Folder ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ftrack_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ftrack Project ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='googlegroup_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Google Group ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slack_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slack Channel ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='xero_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Xero Tracking Category ID'),
        ),
    ]
