# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0002_project_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconnection',
            name='connection_name',
            field=models.CharField(blank=True, default='', help_text='Used by some connection types to differentiate multiple connections', max_length=200),
        ),
    ]
