# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0003_auto_20171206_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconnection',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='serviceconnection',
            name='is_messenger',
            field=models.BooleanField(default=False, help_text='If checked, this channel will receive all Lucid Control messages', verbose_name='Messenger Channel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucid_api.ProjectType', verbose_name='Type'),
        ),
    ]
