# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0003_auto_20171202_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('character_code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Character Code')),
                ('description', models.CharField(max_length=500, verbose_name='Project Type')),
            ],
            options={
                'verbose_name': 'Project Type',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='dropbox_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ftrack_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='googlegroup_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slack_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='xero_id',
        ),
        migrations.AddField(
            model_name='project',
            name='type_code',
            field=models.ForeignKey(default='X', on_delete=django.db.models.deletion.CASCADE, to='lucid_api.ProjectType'),
            preserve_default=False,
        ),
    ]
