# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0004_auto_20171202_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('slack', 'Slack'), ('ftrack', 'ftrack'), ('dropbox', 'dropbox'), ('xero', 'Xero'), ('googlegroups', 'Google groups')], max_length=200, verbose_name='Service Name')),
                ('connection_name', models.CharField(blank=True, max_length=200)),
                ('identifier', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucid_api.Project')),
            ],
        ),
    ]
