# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0004_auto_20171206_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceconnection',
            options={'verbose_name': 'Service Connection'},
        ),
        migrations.AlterModelOptions(
            name='templateserviceconnection',
            options={'verbose_name': 'Template Project', 'verbose_name_plural': 'Template Project'},
        ),
    ]
