# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_api', '0005_auto_20171206_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If checked, this will be used as the type when creating new projects via the api', verbose_name='Default Project Type'),
        ),
    ]
