# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Checkin Date')),
                ('initial_action', models.DateTimeField(auto_now_add=True, verbose_name='Initial Action Time')),
                ('last_action', models.DateTimeField(auto_now=True, verbose_name='Last Action Time')),
            ],
        ),
        migrations.CreateModel(
            name='WorkdayOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('flex_adjustment', models.FloatField(help_text='Whether to add or remove flex days. Decimal days are acceptable', verbose_name='Flex Days Adjustment')),
                ('vacation_penalty', models.BooleanField(default=False, help_text='Whether or not this day reduces vacation days', verbose_name='Vacation Penalty')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='workday',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='checkin.WorkdayOption'),
        ),
        migrations.AddField(
            model_name='workday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='checkin.Profile'),
        ),
    ]
