# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0005_auto_20180102_1355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_checkin_beat', models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='django_celery_beat.PeriodicTask', verbose_name='Daily Check-in Schedule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkin User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Checkin Date')),
                ('scheduled', models.DateTimeField(auto_now_add=True, help_text='timestamp from when the checkin was scheduled')),
                ('is_posted', models.BooleanField(default=False, help_text='Whether the check-in has been sent')),
                ('last_action', models.DateTimeField(auto_now=True, verbose_name='Last Action Time')),
                ('slack_message_ts', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Slack message_ts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='checkin.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkdayOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('emoji', models.CharField(blank=True, max_length=200, verbose_name='Emoji Text')),
                ('flex_adjustment', models.FloatField(help_text='Whether to add or remove flex days. Decimal days are acceptable', verbose_name='Flex Days Adjustment')),
                ('vacation_penalty', models.BooleanField(default=False, help_text='Whether or not this day reduces vacation days', verbose_name='Vacation Day Penalty')),
                ('sick_penalty', models.BooleanField(default=False, help_text='Whether or not this day reduces sick days', verbose_name='Sick Day Penalty')),
                ('is_active', models.BooleanField(default=True)),
                ('require_confirmation', models.BooleanField(default=False, help_text='Whether or not to require the user to confirm')),
                ('confirmation_text', models.CharField(blank=True, default='', help_text='Only applied when confirmation is required', max_length=500)),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('default', 'Default'), ('danger', 'Danger')], default='default', max_length=50)),
                ('sort_order', models.IntegerField(unique=True, verbose_name='Display order for options. Must be unique.')),
            ],
        ),
        migrations.CreateModel(
            name='WorkdayResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slack_action_ts', models.CharField(default='', max_length=100, verbose_name='Slack action_ts')),
                ('response', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='checkin.WorkdayOption')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checkin.Workday')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
    ]
