# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='initial_action',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the checkin is scheduled for'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='is_posted',
            field=models.BooleanField(default=False, help_text='Whether the check-in has been sent'),
        ),
        migrations.AddField(
            model_name='workday',
            name='scheduled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='timestamp from when the checkin was scheduled'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workday',
            name='response',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='checkin.WorkdayOption'),
        ),
    ]
