# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slack_user',
            field=models.CharField(help_text='This should be something like <em>U1ADJNUJX</em>', max_length=50, verbose_name='Slack Member ID'),
        ),
    ]
