# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20180201_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slack_user',
            field=models.CharField(help_text='This should be something like <strong>U1ADJNUJX</strong>', max_length=50, verbose_name='Slack Member ID'),
        ),
    ]
