# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20171227_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': ('Checkin User',), 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='workdayoption',
            name='confirmation_text',
            field=models.CharField(blank=True, default='', help_text='Only applied when confirmation is required', max_length=500),
        ),
        migrations.AddField(
            model_name='workdayoption',
            name='emoji',
            field=models.CharField(blank=True, max_length=200, verbose_name='Emoji Text'),
        ),
        migrations.AddField(
            model_name='workdayoption',
            name='require_confirmation',
            field=models.BooleanField(default=False, help_text='Whether or not to require the user to confirm'),
        ),
        migrations.AddField(
            model_name='workdayoption',
            name='style',
            field=models.CharField(choices=[('primary', 'Primary'), ('', 'Default'), ('danger', 'Danger')], default='', max_length=50),
        ),
    ]
