# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20171223_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdayoption',
            name='sort_order',
            field=models.IntegerField(default=1, verbose_name='Display order for options. Must be unique.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workdayoption',
            name='style',
            field=models.CharField(choices=[('primary', 'Primary'), ('default', 'Default'), ('danger', 'Danger')], default='default', max_length=50),
        ),
    ]
