# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_profile_daily_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdayresponse',
            name='response',
        ),
        migrations.RemoveField(
            model_name='workdayresponse',
            name='workday',
        ),
        migrations.AddField(
            model_name='workday',
            name='response',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='checkin.WorkdayOption', verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='slack_action_ts',
            field=models.CharField(default='', max_length=100, verbose_name='Slack action_ts'),
        ),
        migrations.DeleteModel(
            name='WorkdayResponse',
        ),
    ]
