# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_profile_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
