# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20180102_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick'), ('flex', 'Flex')], max_length=100)),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrued_days_off', to='checkin.Profile')),
            ],
        ),
    ]
