# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20171223_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdayoption',
            name='sort_order',
            field=models.IntegerField(unique=True, verbose_name='Display order for options. Must be unique.'),
        ),
    ]
