# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_dayoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdayoption',
            name='flex_adjustment',
        ),
        migrations.RemoveField(
            model_name='workdayoption',
            name='sick_penalty',
        ),
        migrations.RemoveField(
            model_name='workdayoption',
            name='vacation_penalty',
        ),
        migrations.AddField(
            model_name='dayoff',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workdayoption',
            name='time_off_adjustment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workdayoption',
            name='time_off_type',
            field=models.CharField(blank=True, choices=[('vacation', 'Vacation'), ('sick', 'Sick'), ('flex', 'Flex')], max_length=100, null=True),
        ),
    ]
