# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_auto_20171223_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdayoption',
            name='sick_penalty',
            field=models.BooleanField(default=False, help_text='Whether or not this day reduces sick days', verbose_name='Sick Day Penalty'),
        ),
        migrations.AlterField(
            model_name='workdayoption',
            name='vacation_penalty',
            field=models.BooleanField(default=False, help_text='Whether or not this day reduces vacation days', verbose_name='Vacation Day Penalty'),
        ),
    ]
