# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-21 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_auto_20180202_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayoff',
            options={'verbose_name': 'Day Off', 'verbose_name_plural': 'Days Off'},
        ),
        migrations.RemoveField(
            model_name='workday',
            name='is_posted',
        ),
    ]
