# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_auto_20171223_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkdayResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='checkin.WorkdayOption')),
            ],
        ),
        migrations.RemoveField(
            model_name='workday',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='response',
        ),
        migrations.AddField(
            model_name='workdayresponse',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checkin.Workday'),
        ),
    ]
