# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_auto_20180102_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='amount',
            field=models.FloatField(help_text='Number of days to add. Decimals OK', verbose_name='Days'),
        ),
    ]
