# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_auto_20171223_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Checkin User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='workdayresponse',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AddField(
            model_name='workday',
            name='slack_message_ts',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Slack message_ts'),
        ),
        migrations.AddField(
            model_name='workdayresponse',
            name='slack_action_ts',
            field=models.CharField(default='', max_length=100, verbose_name='Slack action_ts'),
        ),
    ]
