# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_auto_20180102_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='checkin.WorkdayOption', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workdayoption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
