# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_auto_20171231_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='slack_message_ts',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Slack message_ts'),
        ),
    ]
